using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using PosSystem.Infrastructure;
using PosSystem.Modules.Auth.Entities;
using PosSystem.SharedKernel;
using PosSystem.SharedKernel.Interfaces;

namespace PosSystem.Modules.Auth.Services;

public class AuthProvisionerService(PosDbContext db) : IAuthProvisioner
{

    // the AuthProvisioner is responsible for creating the AppUser credentials in the Auth module when a new user is created
    public async Task<Result<bool>> CreateCredentialsAsync(Guid userId,string email, string plainTextPassword, CancellationToken ct=default)
    {
        var credentials = new AppUser
        {
        Id = userId, // we use the exact same ID generated by the Users module
        Email = email,
        PasswordHash = BCrypt.Net.BCrypt.HashPassword(plainTextPassword)


        };

        db.Set<AppUser>().Add(credentials);
        await db.SaveChangesAsync(ct);
        return Result<bool>.Ok(true);
    }

}